/* eslint-disable no-unreachable */
import userApiClient from "../";

export const getAllProductsOptions = (data) => {
  return Promise.resolve({
    data: [
      {
        productOptionID: 6,
        productID: 2,
        subscriptionID: 1,
        optionID: 2,
        price: 20000,
        priority: 3,
        isActive: true,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 2,
          title: "چهار هسته ای",
          optionTypeID: 1,
          value: 4,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 7,
        productID: 9,
        subscriptionID: 1,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 9,
          title: "یس2متلب1",
          path: null,
          parameter: null,
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 9,
        productID: 5,
        subscriptionID: 1,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 5,
          title: "متلب",
          path: "c:/NewFolder",
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 100000,
          shortDescription: "تست",
          longDescription: "تست",
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 10,
        productID: 5,
        subscriptionID: 2,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 5,
          title: "متلب",
          path: "c:/NewFolder",
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 100000,
          shortDescription: "تست",
          longDescription: "تست",
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 2,
          title: "سه ماهه",
          subscriptionTypeID: 1,
          value: 0,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 11,
        productID: 7,
        subscriptionID: 1,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 7,
          title: "2متلب1",
          path: "c:/NewFolder",
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 12,
        productID: 7,
        subscriptionID: 1,
        optionID: 2,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 7,
          title: "2متلب1",
          path: "c:/NewFolder",
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 2,
          title: "چهار هسته ای",
          optionTypeID: 1,
          value: 4,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 13,
        productID: 8,
        subscriptionID: 1,
        optionID: 2,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 8,
          title: "ی2متلب1",
          path: null,
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 2,
          title: "چهار هسته ای",
          optionTypeID: 1,
          value: 4,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 14,
        productID: 8,
        subscriptionID: 1,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 8,
          title: "ی2متلب1",
          path: null,
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 15,
        productID: 8,
        subscriptionID: 1,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 8,
          title: "ی2متلب1",
          path: null,
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
      {
        productOptionID: 16,
        productID: 8,
        subscriptionID: 1,
        optionID: 1,
        price: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 8,
          title: "ی2متلب1",
          path: null,
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 0,
          shortDescription: "تست",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        option: {
          optionID: 1,
          title: "دو هسته ای",
          optionTypeID: 1,
          value: 2,
          isActive: true,
          isDelete: false,
          optionType: null,
        },
      },
    ],
    index: 0,
    size: 10,
    count: 15,
  });

  return userApiClient.post("/ProductOption/All", data);
};

export const getProductOption = (productOptionId) => {
  return Promise.resolve({
    productOptionID: 6,
    productID: 2,
    subscriptionID: 1,
    optionID: 2,
    price: 20000,
    priority: 3,
    isActive: true,
    isDelete: false,
    product: {
      productID: 2,
      title: "تست",
      path: "تست",
      parameter: "تستsdvsdf",
      categoryID: 4,
      isActive: true,
      allSoftware: false,
      allowExecuteExe: false,
      serverID: 1,
      hasStock: true,
      stock: 100,
      price: 1000000,
      shortDescription: "",
      longDescription: null,
      softwareName: null,
      softwareInstalledPath: null,
      userID: null,
      createDate: null,
      isDelete: false,
      category: null,
      server: null,
    },
    subscription: {
      subscriptionID: 1,
      title: "یک ماهه",
      subscriptionTypeID: 2,
      value: 42,
      isActive: true,
      isDelete: false,
      subscriptionType: null,
    },
    option: {
      optionID: 2,
      title: "چهار هسته ای",
      optionTypeID: 1,
      value: 4,
      isActive: true,
      isDelete: false,
      optionType: null,
    },
  });

  return userApiClient.get(`/ProductOption/${productOptionId}`);
};

export const addProductOption = (data) => {
  return userApiClient.post("​/ProductOption", data);
};

export const updateProductOPtion = (data) => {
  return userApiClient.put("​/ProductOption", data);
};

export const deleteProductOption = (data) => {
  return userApiClient.delete("​/ProductOption", data);
};
