/* eslint-disable no-unreachable */
import userApiClient from "../";

export const getAllProductsPrices = (data) => {
  return Promise.resolve({
    data: [
      {
        productPriceID: 6,
        productID: 2,
        subscriptionID: 2,
        payTypeID: null,
        price: 3233,
        realPrice: 343332032,
        priority: 34,
        isActive: false,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 2,
          title: "سه ماهه",
          subscriptionTypeID: 1,
          value: 0,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: null,
      },
      {
        productPriceID: 8,
        productID: 2,
        subscriptionID: 1,
        payTypeID: 3,
        price: 100000,
        realPrice: 1000000,
        priority: 1,
        isActive: false,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: {
          payTypeID: 3,
          title: "درگاه بانکی",
          isActive: false,
          isDelete: false,
        },
      },
      {
        productPriceID: 11,
        productID: 2,
        subscriptionID: 2,
        payTypeID: 4,
        price: 100000,
        realPrice: 1000000,
        priority: 1,
        isActive: false,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 2,
          title: "سه ماهه",
          subscriptionTypeID: 1,
          value: 0,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: {
          payTypeID: 4,
          title: "کارت به کارت",
          isActive: false,
          isDelete: false,
        },
      },
      {
        productPriceID: 12,
        productID: 2,
        subscriptionID: 2,
        payTypeID: 4,
        price: 100000,
        realPrice: 1000000,
        priority: 1,
        isActive: false,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 2,
          title: "سه ماهه",
          subscriptionTypeID: 1,
          value: 0,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: {
          payTypeID: 4,
          title: "کارت به کارت",
          isActive: false,
          isDelete: false,
        },
      },
      {
        productPriceID: 13,
        productID: 2,
        subscriptionID: 2,
        payTypeID: 4,
        price: 100000,
        realPrice: 1000000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 2,
          title: "سه ماهه",
          subscriptionTypeID: 1,
          value: 0,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: {
          payTypeID: 4,
          title: "کارت به کارت",
          isActive: false,
          isDelete: false,
        },
      },
      {
        productPriceID: 28,
        productID: 2,
        subscriptionID: 1,
        payTypeID: 4,
        price: 100000,
        realPrice: 1000000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: {
          payTypeID: 4,
          title: "کارت به کارت",
          isActive: false,
          isDelete: false,
        },
      },
      {
        productPriceID: 29,
        productID: 5,
        subscriptionID: 1,
        payTypeID: null,
        price: 100075600,
        realPrice: 1000675600,
        priority: 2,
        isActive: true,
        isDelete: false,
        product: {
          productID: 5,
          title: "متلب",
          path: "c:/NewFolder",
          parameter: "config",
          categoryID: 2,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: true,
          serverID: 1,
          hasStock: true,
          stock: 10,
          price: 100000,
          shortDescription: "تست",
          longDescription: "تست",
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: null,
      },
      {
        productPriceID: 30,
        productID: 2,
        subscriptionID: 1,
        payTypeID: null,
        price: 100000,
        realPrice: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: null,
      },
      {
        productPriceID: 31,
        productID: 2,
        subscriptionID: 1,
        payTypeID: null,
        price: 100000,
        realPrice: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 1,
          title: "یک ماهه",
          subscriptionTypeID: 2,
          value: 42,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: null,
      },
      {
        productPriceID: 33,
        productID: 2,
        subscriptionID: 2,
        payTypeID: null,
        price: 100000,
        realPrice: 100000,
        priority: 1,
        isActive: true,
        isDelete: false,
        product: {
          productID: 2,
          title: "تست",
          path: "تست",
          parameter: "تستsdvsdf",
          categoryID: 4,
          isActive: true,
          allSoftware: false,
          allowExecuteExe: false,
          serverID: 1,
          hasStock: true,
          stock: 100,
          price: 1000000,
          shortDescription: "",
          longDescription: null,
          softwareName: null,
          softwareInstalledPath: null,
          userID: null,
          createDate: null,
          isDelete: false,
          category: null,
          server: null,
        },
        subscription: {
          subscriptionID: 2,
          title: "سه ماهه",
          subscriptionTypeID: 1,
          value: 0,
          isActive: true,
          isDelete: false,
          subscriptionType: null,
        },
        payType: null,
      },
    ],
    index: 0,
    size: 10,
    count: 11,
  });
  return userApiClient.post("/ProductPrice/All", data);
};

export const getProductsPrice = (productPrice) => {
  return Promise.resolve({
    productPriceID: 6,
    productID: 2,
    subscriptionID: 2,
    payTypeID: null,
    price: 3233,
    realPrice: 343332032,
    priority: 34,
    isActive: false,
    isDelete: false,
    product: {
      productID: 2,
      title: "تست",
      path: "تست",
      parameter: "تستsdvsdf",
      categoryID: 4,
      isActive: true,
      allSoftware: false,
      allowExecuteExe: false,
      serverID: 1,
      hasStock: true,
      stock: 100,
      price: 1000000,
      shortDescription: "",
      longDescription: null,
      softwareName: null,
      softwareInstalledPath: null,
      userID: null,
      createDate: null,
      isDelete: false,
      category: null,
      server: null,
    },
    subscription: {
      subscriptionID: 2,
      title: "سه ماهه",
      subscriptionTypeID: 1,
      value: 0,
      isActive: true,
      isDelete: false,
      subscriptionType: null,
    },
    payType: null,
  });

  return userApiClient.get(`/ProductPrice/${productPrice}`);
};

export const addProductsPrice = (data) => {
  return userApiClient.post("​/ProductPrice", data);
};

export const updateProductsPrice = (data) => {
  return userApiClient.put("​/ProductPrice", data);
};

export const deleteProductsPrice = (data) => {
  return userApiClient.delete("​/ProductPrice", data);
};
