/* eslint-disable no-unreachable */
import userApiClient from "../";

export const getAllPersons = (data) => {
  // return Promise.resolve({
  //   data: {
  //     data: [
  //       {
  //         PersonID: 1,
  //         UserName: "mohsen",
  //         Password: "123",
  //         FirstName: "mohsen",
  //         LastName: "lotfi",
  //         NationalCode: "0370207904",
  //         Email: "pro.cs.mohsen@gmail.com",
  //         Phone: "025-12345678",
  //         Mobile: "09195421787",
  //         ZipCode: "12345-67890",
  //         StateID: 22,
  //         Address: "پردیسان مروارید4",
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: "2021-08-17T20:59:49.570Z",
  //         State: null,
  //       },
  //       {
  //         PersonID: 1,
  //         UserName: "mohsen",
  //         Password: "123",
  //         FirstName: "mohsen",
  //         LastName: "lotfi",
  //         NationalCode: "0370207904",
  //         Email: "pro.cs.mohsen@gmail.com",
  //         Phone: "025-12345678",
  //         Mobile: "09195421787",
  //         ZipCode: "12345-67890",
  //         StateID: 22,
  //         Address: "پردیسان مروارید4",
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 7,
  //         UserName: "taha",
  //         Password: "taha",
  //         FirstName: null,
  //         LastName: null,
  //         NationalCode: "0370832272",
  //         Email: "info@gmail.com",
  //         Phone: null,
  //         Mobile: "09191512159",
  //         ZipCode: null,
  //         StateID: 23,
  //         Address: null,
  //         IsActive: false,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 8,
  //         UserName: "kdfhjsdgf",
  //         Password: "dfdsfs",
  //         FirstName: "gfdg",
  //         LastName: "dfgdf",
  //         NationalCode: "0370832272",
  //         Email: "mahdisa.m72@gmail.com",
  //         Phone: null,
  //         Mobile: "09191512159",
  //         ZipCode: null,
  //         StateID: 31,
  //         Address: null,
  //         IsActive: false,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 9,
  //         UserName: "Mina",
  //         Password: "79409c046934219ce6394df684b06f85",
  //         FirstName: "Mina",
  //         LastName: "Mohammadi",
  //         NationalCode: null,
  //         Email: null,
  //         Phone: null,
  //         Mobile: "09379672366",
  //         ZipCode: null,
  //         StateID: 31,
  //         Address: null,
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 10,
  //         UserName: "thgh",
  //         Password: "79409c046934219ce6394df684b06f85",
  //         FirstName: "Mina",
  //         LastName: "Mohammadi",
  //         NationalCode: null,
  //         Email: "mohammadi@g.v",
  //         Phone: null,
  //         Mobile: "09379672367",
  //         ZipCode: null,
  //         StateID: 23,
  //         Address: null,
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 11,
  //         UserName: "afgfg",
  //         Password: "79409c046934219ce6394df684b06f85",
  //         FirstName: "Mina",
  //         LastName: "Mohammadi",
  //         NationalCode: null,
  //         Email: "moham1madi@g.v",
  //         Phone: null,
  //         Mobile: "09307967666",
  //         ZipCode: null,
  //         StateID: 19,
  //         Address: null,
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 12,
  //         UserName: "rfdfsdf",
  //         Password: "79409c046934219ce6394df684b06f85",
  //         FirstName: "Minaaaa",
  //         LastName: "Mohammadiiii",
  //         NationalCode: "0099880458",
  //         Email: "moha0mo1imad0i@gf.bg",
  //         Phone: "025884444449415",
  //         Mobile: "09308888888",
  //         ZipCode: "999999",
  //         StateID: 29,
  //         Address: "rrقم",
  //         IsActive: false,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 13,
  //         UserName: "gghhgfh",
  //         Password: "79409c046934219ce6394df684b06f85",
  //         FirstName: "Mina",
  //         LastName: "Mohammadi",
  //         NationalCode: "0386502536",
  //         Email: "mohamo1imadi@g.v",
  //         Phone: "025889415",
  //         Mobile: "09307917066",
  //         ZipCode: null,
  //         StateID: 27,
  //         Address: null,
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 15,
  //         UserName: "xfdgdg",
  //         Password: "79409c046934219ce6394df684b06f85",
  //         FirstName: "Mina",
  //         LastName: "Mohammadi",
  //         NationalCode: "0759502285",
  //         Email: "moha0mo1imadi@g.v",
  //         Phone: "025889415",
  //         Mobile: "09307910066",
  //         ZipCode: "321876583",
  //         StateID: 2,
  //         Address: null,
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //       {
  //         PersonID: 18,
  //         UserName: "Mina16",
  //         Password: "f2d4b6f89f8454b4f7dceb8ee339a268",
  //         FirstName: "Mina",
  //         LastName: "Mohammadi",
  //         NationalCode: "0680391681",
  //         Email: "oomoha0mo1imad0i@g.v",
  //         Phone: "025889415",
  //         Mobile: "09397918866",
  //         ZipCode: "321876583",
  //         StateID: 1,
  //         Address: "قم",
  //         IsActive: true,
  //         StatusID: null,
  //         WinUser: null,
  //         WinUserType: null,
  //         Salt: null,
  //         Domain: null,
  //         UserID: null,
  //         CreateDate: null,
  //         State: null,
  //       },
  //     ],
  //     index: 0,
  //     size: 10,
  //     count: 13,
  //   },
  // });

  return userApiClient.post("/Person/All", data);
};

export const getPerson = (personId) => {
  // return Promise.resolve({
  //   data: {
  //     PersonID: 19,
  //     UserName: "Mina6",
  //     Password: "4bf69167fb1449a6195178d6202c1c44",
  //     FirstName: "Mina",
  //     LastName: "Mohammadi",
  //     NationalCode: "0209143460",
  //     Email: "moha0mo1imad0i@g.v",
  //     Phone: "025889415",
  //     Mobile: "09307918866",
  //     ZipCode: "321876583",
  //     StateID: 1,
  //     Address: "قم",
  //     IsActive: true,
  //     StatusID: null,
  //     WinUser: null,
  //     WinUserType: null,
  //     Salt: null,
  //     Domain: null,
  //     UserID: null,
  //     CreateDate: null,
  //     State: null,
  //   },
  // });

  return userApiClient.get(`/Person/${personId}`);
};

export const addPerson = (data) => {
  return userApiClient.post("​/Person", data);
};

export const updatePerson = (data) => {
  return userApiClient.put("​/Person", data);
};

export const deletePerson = (data) => {
  return userApiClient.delete("​/Person", data);
};
