<template>
  <EditGroupedDataCard
    title="title"
    icon="cil-applications"
    store-icon="cil-applications"
    store-link="/admin/profileperson/"
    store-name="همه خطی مشی‌های کاربران"
    :fields="fields"
    storePageName="storeProfilePerson"
    :fetchInfoMethod="getOne"
    :updateInfoMethod="update"
    :keysToPost="keysToPost"
  />
</template>

<script>
import {
  add,
  update,
  remove,
  getOne,
} from "../../../../services/Profile/person";
import EditGroupedDataCard from "../../../../components/base/EditGroupedDataCard.vue";
export default {
  components: { EditGroupedDataCard },
  data() {
    return {
      add,
      update,
      remove,
      getOne,
      keysToPost: [
        "isDefault",
        "profileName",
        "autoRemote",
        "colorDepthID",
        "cachePersistenceActive",
        "enableAutoReconnect",
        "maxReconnectAttempts",
        "redirectDrives",
        "redirectPrinters",
        "redirectClipboard",
        "redirectSmartCards",
        "redirectPorts",
        "redirectDevices",
        "redirectPOSDevices",
        "audioRedirectionMode",
        "disablE_CURSOR_SHADOW",
        "disablE_CURSORSETTINGS",
        "disablE_FULLWINDOWDRAG",
        "disablE_MENUANIMATIONS",
        "disablE_THEMING",
        "disablE_WALLPAPER",
        "enablE_DESKTOP_COMPOSITION",
        "enablE_ENHANCED_GRAPHICS",
        "enablE_FONT_SMOOTHING",
        "softwareRunNumber",
        "softwareRunLength",
        "softwareRunTimeFrom",
        "softwareRunTimeTo",
        "softwareRunSaturday",
        "softwareRunSunday",
        "softwareRunMonday",
        "softwareRunTuesday",
        "softwareRunWednesday",
        "softwareRunThursday",
        "softwareRunFriday",
        "disableDrives",
        "restrictDrives",
        "disableCMD",
        "disableRegistry",
        "disableGPEdit",
        "disableMapDrive",
        "disableShare",
        "disableTaskManager",
        "disableControlPanel",
        "webServer",
        "accessDesktop",
        "disableFolderOption",
        "disableShutdwon",
        "webRedirectDrive",
        "webRedirectPrinter",
        "webColorDepthID",
        "webAudio",
        "webScreenWidth",
        "webScreenHeight",
        "autoLogOffTime",
        "quotaLimitSize",
        "cpuCoreNumber",
        "enableProcessWatcher",
        "showUserProfile",
        "ipFrom",
        "ipTo",
        "storageID",
        "enableNetworkDiscovery",
        "limitTypeID",
        "downloadTrafficLimit",
        "uploadTrafficLimit",
        "downloadUploadTrafficLimit",
        "profileID",
        "personID",
        "profilePersonID",
      ],
    };
  },
  computed: {
    colorDepthsArr() {
      return this.$store.state.colorDepthsArray.map((stateObj) => ({
        label: stateObj.title,
        value: stateObj.id,
      }));
    },
    storagesArr() {
      return this.$store.state.storagesArray.map((stateObj) => ({
        label: stateObj.title,
        value: stateObj.id,
      }));
    },
    limitTypesArr() {
      return this.$store.state.limitTypesArray.map((stateObj) => ({
        label: stateObj.title,
        value: stateObj.id,
      }));
    },
    personsArr() {
      return this.$store.state.personsArray.map((stateObj) => ({
        label: stateObj.title,
        value: stateObj.id,
      }));
    },
    profilesArr() {
      return this.$store.state.profilesArray.map((stateObj) => ({
        label: stateObj.title,
        value: stateObj.id,
      }));
    },
    fields() {
      const self = this;
      return [
        {
          headerName: "تنظیمات خط مشی",
          col: "12",
          children: [
            {
              name: "profile.profileName",
              type: "text",
              persianLabel: "عنوان خط مشی",
              col: "6",
              isRequired: true,
              validationFunction: (val) => val && val !== "",
              invalidFeedback: "عنوان خط مشی را وارد کنید",
            },
            {
              name: "personID",
              type: "option",
              persianLabel: "کاربر",
              options: self.personsArr,
              col: "6",
              isRequired: true,
              validationFunction: (val) => val,
              invalidFeedback: "کاربر را انتخاب کنید",
            },
            {
              name: "profile.isDefault",
              type: "switch",
              persianLabel: "پیشفرض",
              col: "6",
            },
          ],
        },
        {
          headerName: "نمایش",
          col: "6",
          children: [
            {
              name: "colorDepthID",
              type: "option",
              persianLabel: "عمق رنگ",
              options: self.colorDepthsArr,
              col: "6",
              isRequired: false,
              validationFunction: (val) => !val || val,
              invalidFeedback: "عمق رنگ را انتخاب کنید",
            },
            {
              name: "cachePersistenceActive",
              type: "number",
              persianLabel: "نهان ساز",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "نهان ساز را مشخص کنید",
            },
          ],
        },
        {
          headerName: "دسترسی سخت‌افزار",
          col: "6",
          children: [
            {
              name: "audioRedirectionMode",
              type: "checkbox",
              persianLabel: "صدا",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "صدا را مشخص کنید",
            },
            {
              name: "redirectClipboard",
              type: "checkbox",
              persianLabel: "کلیپ برد",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "کلیپ برد را مشخص کنید",
            },
            {
              name: "redirectDevices",
              type: "checkbox",
              persianLabel: "ابزار های متصل",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "ابزار های متصل را مشخص کنید",
            },
            {
              name: "redirectSmartCards",
              type: "checkbox",
              persianLabel: "کارت های هوشمند",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "کارت های هوشمند را مشخص کنید",
            },
            {
              name: "redirectPorts",
              type: "checkbox",
              persianLabel: "پورت های سریال",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "پورت های سریال را مشخص کنید",
            },
            {
              name: "redirectPOSDevices",
              type: "checkbox",
              persianLabel: "دستگاه های متصل همراه",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "دستگاه های متصل همراه را مشخص کنید",
            },
            {
              name: "redirectDrives",
              type: "checkbox",
              persianLabel: "درایو‌ها",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "درایو‌ها را مشخص کنید",
            },
            {
              name: "redirectPrinters",
              type: "checkbox",
              persianLabel: "پرینتر محلی",
              col: "2",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "پرینتر محلی را مشخص کنید",
            },
          ],
        },
        {
          headerName: "زمان",
          col: "6",
          children: [
            {
              name: "softwareRunSaturday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز شنبه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز شنبه را مشخص کنید",
            },
            {
              name: "softwareRunSunday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز یکشنبه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز یکشنبه را مشخص کنید",
            },
            {
              name: "softwareRunMonday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز دوشنبه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز دوشنبه را مشخص کنید",
            },
            {
              name: "softwareRunTuesday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز سه‌شنبه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز سه‌شنبه را مشخص کنید",
            },
            {
              name: "softwareRunWednesday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز چهارشنبه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز چهارشنبه را مشخص کنید",
            },
            {
              name: "softwareRunThursday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز پنج‌شنبه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز پنج‌شنبه را مشخص کنید",
            },
            {
              name: "softwareRunFriday",
              type: "checkbox",
              persianLabel: "اجرا برنامه در روز جمعه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "اجرا برنامه در روز پنج‌شنبه را مشخص کنید",
            },
            {
              name: "autoLogOffTime",
              type: "number",
              persianLabel: "زمان لاگ آف کاربر",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "زمان لاگ آف کاربر را مشخص کنید",
            },
            {
              name: "softwareRunNumber",
              type: "number",
              persianLabel: "دفعات اجرا",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "دفعات اجرا را مشخص کنید",
            },
            {
              name: "softwareRunLength",
              type: "number",
              persianLabel: "مدت اجرای برنامه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "مدت اجرای برنامه را مشخص کنید",
            },
            {
              name: "softwareRunTimeFrom",
              type: "number",
              persianLabel: "محدوده زمانی اجرا از",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "محدوده زمانی اجرا از را مشخص کنید",
            },
            {
              name: "softwareRunTimeTo",
              type: "number",
              persianLabel: "محدوده زمانی اجرا تا",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "محدوده زمانی اجرا تا را مشخص کنید",
            },
          ],
        },
        {
          headerName: "دسترسی‌ها",
          col: "6",
          children: [
            {
              name: "disableDrives",
              type: "checkbox",
              persianLabel: "مخفی شدن درایوها",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "مخفی شدن درایوها را مشخص کنید",
            },
            {
              name: "disableMapDrive",
              type: "checkbox",
              persianLabel: "غیرفعال شدن درایو شبکه",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن درایو شبکه را مشخص کنید",
            },
            {
              name: "restrictDrives",
              type: "checkbox",
              persianLabel: "عدم دسترسی درایوها",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "عدم دسترسی درایوها را مشخص کنید",
            },
            {
              name: "disableRegistry",
              type: "checkbox",
              persianLabel: "غیرفعال شدن Registery",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن Registery را مشخص کنید",
            },
            {
              name: "disableGPEdit",
              type: "checkbox",
              persianLabel: "غیرفعال شدن GEEdit",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن GEEdit را مشخص کنید",
            },
            {
              name: "disableTaskManager",
              type: "checkbox",
              persianLabel: "غیرفعال شدن TaskManager",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن TaskManager را مشخص کنید",
            },
            {
              name: "disableControlPanel",
              type: "checkbox",
              persianLabel: "غیرفعال شدن ControlPanel",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن ControlPanel را مشخص کنید",
            },
            {
              name: "disableCMD",
              type: "checkbox",
              persianLabel: "غیرفعال شدن CMD",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن GEEdit را مشخص کنید",
            },
            {
              name: "disableFolderOption",
              type: "checkbox",
              persianLabel: "غیرفعال شدن Folder Option",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال شدن Folder Option را مشخص کنید",
            },
            {
              name: "disableShare",
              type: "checkbox",
              persianLabel: "غیرفعال بودن اشتراک",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "غیرفعال بودن اشتراک را مشخص کنید",
            },
            {
              name: "showUserProfile",
              type: "checkbox",
              persianLabel: "مخفی نشدن پروفایل کاربر",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "مخفی نشدن پروفایل کاربر را مشخص کنید",
            },
            {
              name: "enableProcessWatcher",
              type: "checkbox",
              persianLabel: "بستن برنامه های غیر مجاز",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "بستن برنامه های غیر مجاز را مشخص کنید",
            },
            {
              name: "enableNetworkDiscovery",
              type: "checkbox",
              persianLabel: "فعال شدن Network Discovery",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "فعال شدن Network Discovery را مشخص کنید",
            },
            {
              name: "cpuCoreNumber",
              type: "number",
              persianLabel: "تعداد هسته CPU مجاز",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "تعداد هسته CPU مجاز را مشخص کنید",
            },
            {
              name: "storageID",
              type: "option",
              persianLabel: "فضای ذخیره سازی",
              options: self.storagesArr,
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "فضای ذخیره سازی را مشخص کنید",
            },
            {
              name: "quotaLimitSize",
              type: "number",
              persianLabel: "میزان فضای مجاز کاربر(MB)",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "میزان فضای مجاز کاربر(MB) را مشخص کنید",
            },
            {
              name: "ipFrom",
              type: "text",
              persianLabel: "دسترسی IP از",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "دسترسی IP از را مشخص کنید",
            },
            {
              name: "ipTo",
              type: "text",
              persianLabel: "دسترسی IP تا",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "دسترسی IP تا را مشخص کنید",
            },
            {
              name: "accessDesktop",
              type: "checkbox",
              persianLabel: "دسترسی دسکتاپ",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "دسترسی دسکتاپ را مشخص کنید",
            },
          ],
        },
        {
          headerName: "دسترسی‌ وب",
          col: "6",
          children: [
            {
              name: "webServer",
              type: "checkbox",
              persianLabel: "دسترسی از طریق وب",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "دسترسی از طریق وب را مشخص کنید",
            },

            {
              name: "webRedirectDrive",
              type: "text",
              persianLabel: "Web Redirect Drive",
              col: "6",
              validationFunction: (val) => !val || (val && val !== ""),
              invalidFeedback: "Web Redirect Drive را مشخص کنید",
            },
            {
              name: "webRedirectPrinter",
              type: "text",
              persianLabel: "Web Redirect Printer",
              col: "6",
              validationFunction: (val) => !val || (val && val !== ""),
              invalidFeedback: "Web Redirect Printer را مشخص کنید",
            },

            {
              name: "webScreenWidth",
              type: "number",
              persianLabel: "غیرفعال بودن Web Screen Width",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "Web Screen Width را مشخص کنید",
            },
            {
              name: "webScreenHeight",
              type: "number",
              persianLabel: "غیرفعال بودن Web Screen Height",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "Web Screen Height را مشخص کنید",
            },
            {
              name: "webAudio",
              type: "text",
              persianLabel: "Web Audio",
              col: "6",
              validationFunction: (val) => !val || (val && val !== ""),
              invalidFeedback: "Web Audio را مشخص کنید",
            },
            {
              name: "webColorDepthID",
              type: "option",
              options: self.colorDepthsArr,
              persianLabel: "عمق رنگ وب",
              col: "6",
              validationFunction: (val) => !val || val,
              invalidFeedback: "عمق رنگ وب را مشخص کنید",
            },
          ],
        },
        {
          headerName: "اینترنت",
          col: "6",
          children: [
            {
              name: "limitTypeID",
              type: "option",
              persianLabel: "نوع محدودیت حجمی",
              options: self.limitTypesArr,
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "نوع محدودیت حجمی را مشخص کنید",
            },
            {
              name: "downloadTrafficLimit",
              type: "number",
              persianLabel: "Download Traffic Limit",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "Download Traffic Limit را مشخص کنید",
            },
            {
              name: "uploadTrafficLimit",
              type: "number",
              persianLabel: "Upload Traffic Limit",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "Upload Traffic Limit را مشخص کنید",
            },
            {
              name: "downloadUploadTrafficLimit",
              type: "number",
              persianLabel: "Download Upload Traffic Limit",
              col: "6",
              validationFunction: (val) => !val || (val && !Number.isNaN(val)),
              invalidFeedback: "Download Upload Traffic Limit را مشخص کنید",
            },
          ],
        },
      ];
    },
  },
};
</script>